apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airtable-enrichment.fullname" . }}
  labels:
    {{- include "airtable-enrichment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "airtable-enrichment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airtable-enrichment.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name : acr-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AIRTABLE_URL
              value: {{ .Values.airtable.url | quote }}
            - name: AIRTABLE_TOKEN
              value: {{ .Values.airtable.token | quote }}
            - name: BEARER_TOKEN
              value: {{ .Values.airtable.bearer | quote }}
