apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-fuzzy-purchase-order-enrichment.fullname" . }}
  labels:
    {{- include "helm-fuzzy-purchase-order-enrichment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-fuzzy-purchase-order-enrichment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-fuzzy-purchase-order-enrichment.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name : acr-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AIRTABLE_API_KEY
              value: {{ .Values.airtable.AIRTABLE_API_KEY | quote }}
            - name: AIRTABLE_BASE
              value: {{ .Values.airtable.AIRTABLE_BASE | quote }}

